export const GET_SEARCH_DATA_REQUEST = 'GET_SEARCH_DATA_REQUEST';
export const GET_SEARCH_DATA_RESPONSE = 'GET_SEARCH_DATA_RESPONSE';
export const SET_SEARCH_NAME_ACTION_DATA = 'SET_SEARCH_NAME_ACTION_DATA';